tên: CI



bật: [push, workflow_dispatch]



công việc:


  xây dựng:



    chạy trên: windows-mới nhất



    các bước:


    - tên: Tải xuống


      chạy: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip


    - tên: Trích xuất


      chạy: Mở rộng-Lưu trữ ngrok.zip


    - tên: Xác thực


      chạy: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN


      vi:


        NGROK_AUTH_TOKEN: ${{ bí mật.NGROK_AUTH_TOKEN }}


    - tên: Kích hoạt TS


      chạy: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0


    - chạy: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"


    - chạy: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Giá trị 1


    - chạy: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)


    - tên: Tạo đường hầm


      chạy: .\ngrok\ngrok.exe tcp 3389
